### ISSUE TITLE
Support for Raphael 2?

### ISSUE THREAD

**Issue by maedi** [n0nick/raphael-linechart#6]
Getting a few 'b is undefined' type errors when using with Raphael 2.1. Does this library support 2?

**Comment by n0nick** [comment]
Hi,

Actually I haven't tested the plugin on Raphael 2 yet. I hope to do so soon. 

Can you provide the full JS error message in the mean time (incl. line number etc.). I might be able to patch the problem for now.

**Comment by maedi** [comment]
Testing again everything seems to be working well with Raphael 2.1, I think it was my human error initially. The only issue is that the 'line text' and the popup aren't positioning above the points correctly, and are instead floating to the left.

**Comment by n0nick** [comment]
Sorry about the delay in responding.
Could you describe the problem more thoroughly, and perhaps post a screenshot?
Thanks a bunch.

**Comment by usman000** [comment]
n0nick.... the demo is stucking alot when you hover on the graph points in IE8. kindly solve it asap. Im stcuked coz of ths issue. :(

**Comment by n0nick** [comment]
I merged from @tbernier's fork and it fixes support for Raphael 2.1.
There is another issue in the demo page which is unrelated (I reproduced it in the older version too) - loading data from the #d2 table doesn't work well. I'll take a look at it tonight.
