### ISSUE TITLE
Support for Multi-line Graphs

### ISSUE THREAD

**Issue by maedi** [n0nick/raphael-linechart#7]
I've had a quick look through the code. Are you able to give any direction on how to add another line on the graph, without replacing the existing line?

**Comment by n0nick** [comment]
I actually thought about adding support for multiple line charts but have not got around to research that yet.
The main JS code is extremely messy right now, as a result of starting from a very different plugin originally. I'll have to clean up the code there (which I'll probably do soon enough) to give an informed answer here.

**Comment by n0nick** [comment]
Please see the demo page on http://n0nick.github.com/raphael-linechart/ and its source code for an example of a multi-line chart.
